# Generated by Django 4.1.7 on 2023-03-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['first_name'], 'verbose_name': 'An Institutes member'},
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
