# Generated by Django 4.1.7 on 2023-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_address_alter_users_college_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
