# Generated by Django 4.1.7 on 2023-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zones',
            name='lat',
            field=models.CharField(db_index=True, default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='zones',
            name='lng',
            field=models.CharField(db_index=True, default=None, max_length=20),
        ),
    ]
