# Generated by Django 4.1.7 on 2023-03-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cities_state_zones_lat_zones_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
