# Generated by Django 4.1.7 on 2023-03-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cities_pincode_alter_cities_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zones',
            name='bounds',
            field=models.JSONField(null=True),
        ),
    ]
