# Generated by Django 4.1.7 on 2023-03-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_zones_zone_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='institutetypes',
            options={'ordering': ['education']},
        ),
        migrations.AlterModelOptions(
            name='zones',
            options={'ordering': ['zone_name']},
        ),
        migrations.AlterModelTable(
            name='cities',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='institutetypes',
            table='institute_types',
        ),
        migrations.AlterModelTable(
            name='zones',
            table='zones',
        ),
    ]
