# Generated by Django 4.1.7 on 2023-03-31 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cities_options_alter_institutetypes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('institute_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institute_name', models.CharField(db_index=True, max_length=50, verbose_name=20)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('website', models.URLField()),
                ('year_of_establishment', models.CharField(max_length=4)),
                ('affiliat_university', models.CharField(max_length=50)),
                ('year_of_affiliation', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=1)),
                ('lat', models.CharField(max_length=10)),
                ('lng', models.CharField(max_length=10)),
                ('college_type', models.CharField(max_length=20)),
                ('is_autonomous', models.BooleanField(default=False)),
                ('has_diploma_courses', models.BooleanField(default=False)),
                ('management', models.CharField(db_index=True, max_length=30)),
                ('is_specialized', models.BooleanField(default=False)),
                ('is_evening_college', models.BooleanField(default=False)),
                ('speciality', models.CharField(db_index=True, max_length=100)),
                ('is_girl_exclusive', models.BooleanField(default=False)),
                ('student_hostel_available', models.BooleanField(default=False)),
                ('hostel_count', models.PositiveIntegerField()),
                ('logo', models.ImageField(upload_to='')),
                ('affiliated_board', models.CharField(choices=[], max_length=200)),
                ('zone_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.zones')),
            ],
            options={
                'db_table': 'colleges',
                'ordering': ['institute_name'],
            },
        ),
    ]
