# Generated by Django 4.1.7 on 2023-03-31 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_colleges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleges',
            old_name='zone_id',
            new_name='zone',
        ),
    ]
