# Generated by Django 4.1.7 on 2023-03-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_zone_id_colleges_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='affiliat_university',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='affiliated_board',
            field=models.CharField(choices=[], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='college_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='hostel_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='speciality',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='year_of_affiliation',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
