# Generated by Django 4.1.7 on 2023-03-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_colleges_affiliat_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='address_lane_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='colleges',
            name='address_lane_2',
            field=models.TextField(null=True),
        ),
    ]
