# Generated by Django 4.1.7 on 2023-03-31 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_colleges_address_lane_1_colleges_address_lane_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-31 08:20:26.555588'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colleges',
            name='created_by',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colleges',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
