# Generated by Django 4.1.7 on 2023-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_colleges_created_at_colleges_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='institute_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
