# Generated by Django 4.1.7 on 2023-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_colleges_institute_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='institute_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
