# Generated by Django 4.1.7 on 2023-03-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_colleges_institute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='affiliat_university',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
