# Generated by Django 4.1.7 on 2023-03-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_colleges_affiliat_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='lat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='lng',
            field=models.CharField(max_length=20),
        ),
    ]
