# Generated by Django 4.1.7 on 2023-03-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_colleges_lat_alter_colleges_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='institute_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
