# Generated by Django 4.1.7 on 2023-03-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_colleges_institute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='college_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='management',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='year_of_affiliation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
