# Generated by Django 4.1.7 on 2023-03-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_colleges_year_of_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
