# Generated by Django 4.1.7 on 2023-04-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leetcodeproblem',
            options={'ordering': ['difficulty']},
        ),
        migrations.AlterModelTable(
            name='leetcodeproblem',
            table='leetcode_problems',
        ),
    ]
