# Generated by Django 4.1.7 on 2023-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leetcode', '0002_alter_leetcodeproblem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='beats_time_complexity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
